#!/usr/bin/env ruby

$LOAD_PATH.unshift "#{Dir.getwd}/lib"

require 'shellopts'

#include ShellOpts::Message
include ShellOpts::Verbose
#include ShellOpts::Debug

#include ShellOpts::Messages
#p ShellOpts::Messages.is_included?

SPEC = %(
  Test

  -a
    An option
)

opts, args = ShellOpts.process(SPEC, ARGV, verbose: false)

verb "Verbose default"
(0..3).each { |i| verb i, "Verbose #{i}" }
mesg "Message"
notice "Notice"
debug "Debug"


